# Generated by Django 4.0.5 on 2022-06-17 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('located', models.CharField(max_length=60)),
                ('occupants_count', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('hood_image', models.ImageField(upload_to='hood_images/')),
                ('police_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('health_dept_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('hood_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('id_number', models.TextField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(upload_to='profiles_pics/')),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('profession', models.CharField(blank=True, max_length=120)),
                ('contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('website', url_or_relative_url_field.fields.URLOrRelativeURLField(blank=True, null=True)),
                ('facebook', url_or_relative_url_field.fields.URLOrRelativeURLField(blank=True, null=True)),
                ('instagram', url_or_relative_url_field.fields.URLOrRelativeURLField(blank=True, null=True)),
                ('twitter', url_or_relative_url_field.fields.URLOrRelativeURLField(blank=True, null=True)),
                ('hood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hoodupdates.hood')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('details', models.TextField(null=True)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood_post', to='hoodupdates.hood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='hoodupdates.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_description', models.TextField(blank=True, max_length=255)),
                ('business_logo', models.ImageField(upload_to='business_logos/')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='hoodupdates.profile')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='hoodupdates.hood')),
            ],
        ),
    ]
