# Generated by Django 4.0.5 on 2022-06-17 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodupdates', '0002_alter_profile_hood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='location',
            new_name='hood',
        ),
        migrations.AlterField(
            model_name='update',
            name='hood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood_updates', to='hoodupdates.hood'),
        ),
    ]
