# Generated by Django 4.0.5 on 2022-06-18 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodupdates', '0003_rename_location_business_hood_alter_update_hood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='hood_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to='hoodupdates.profile'),
        ),
    ]
